Cleaning up API Routes
NCR-Corporation/ncr-retail-demo pull request #52
Opened 2021-07-20 17:31 UTC by kg185155

## Description

The goal here was to do a little code cleanup before the `/health` API endpoint. I updated the responses of the APIs to remove the `{ status }` object in the json and go back to the `res.status()` code that comes with it. There was also some code cleanup in removing console logs and such

2021-07-20 17:32 UTC, kg185155 commented on components/public/ItemCard.js
> +                className={`float-right ${addedToCart && 'fade-btn'}`}
The loading indicator on the cards when items are displayed in a group wasn't working. This fixes that

2021-07-20 17:32 UTC, kg185155 commented on components/public/home/HomeMap.js
> +          {data.response.data.pageContent.map((element) => (
I also organized the response from the `/findSites` endpoint to be better

2021-07-20 17:33 UTC, kg185155 commented on components/public/sites/FindStoreModal.js
> +            const { logs, response } = body;
Same `/findSites` endpoint update

2021-07-20 17:33 UTC, kg185155 commented on lib/hooks/useHomepage.js
> +    const { data, error } = useSWR(`/api/groups`, fetcher);
Previously the api just went to `/api` when it was just fetching groups. I organized that to fetch the correct group route instead of the index route

2021-07-20 17:34 UTC, kg185155 commented on pages/api/index.js
> +  res.status(200).json({ message: 'Welcome to NCR Retail Demo.' });
The code on the left already existed at `/api/groups`, I dont know why it was duplicated. This is now just a dummy route

2021-07-20 22:05 UTC, tm185221 reviewed
Not too sure how to test this one. Everything looks good. I was able to switch sites and view my user profile, so the changes in routes seemed to have not broken anything.

2021-07-22 17:41 UTC, co185063 requested changes

2021-07-22 17:41 UTC, co185063 commented on pages/api/order.js
> +    // Close out the cart.
Comment

2021-07-22 18:01 UTC, merged