Major Code Cleanup
NCR-Corporation/ncr-retail-demo pull request #54
Opened 2021-07-22 12:15 UTC by kg185155

## Description

Please include a description of what this pull request does or what it is trying to solve. This pull requests fixes XYZ or implements ABC.

## Screenshots/Screencasts

If applicable.

## Testing

Please outline how to test this fix or feature. Include all steps.

1. Login to XYZ
2. Click on Button
3. Confirm ABC.

## Ticket

Ticket Number

2021-07-22 15:30 UTC, co185063 approved these changes
LGTM!

2021-09-16 16:31 UTC, co185063 requested changes
I'm going to assume everything works well on your local but I would take this time to double and triple check going through the entire site to make sure nothing is broken. Otherwise please make these small changes I left.

2021-09-16 16:31 UTC, co185063 commented on components/public/home/HomeMap.js
> +  console.log('the data', data.response.data.pageContent);
Console.log()

2021-09-16 16:31 UTC, co185063 commented on pages/catalog.js
> +
extra line

2021-09-16 20:52 UTC, kg185155 commented
@tm185221 @co185063 I found a couple issues and have fixed them in the latest changes. I also made some visual changes in different parts of the site. If you dont mind giving it a QA locally and making sure it all works, that would be greatly appreciated. Want to make sure we are all comfortable with the release

2021-09-20 17:07 UTC, co185063 reviewed
So the only problem that I seem to have is with the map and this console error regarding the map. I would imagine this is an issue with a key though and if it works on your local with an appropriate key then it should be good, but I will give my approval only after you check if the map is working on your local.
![image](https://user-images.githubusercontent.com/72469105/134044115-d8c870c5-b177-4a8b-ae41-817f43c28fd2.png)
![Capture](https://user-images.githubusercontent.com/72469105/134044179-86c98263-a787-4dbf-895f-a58459c1a41f.PNG)

2021-09-30 18:31 UTC, co185063 approved these changes

2021-10-01 17:07 UTC, merged